import { Card, Rank, Suit } from '$lib/poker'

export const aceOfSpades = new Card(Rank.ACE, Suit.SPADES)
export const twoOfSpades = new Card(Rank.TWO, Suit.SPADES)
export const threeOfSpades = new Card(Rank.THREE, Suit.SPADES)
export const fourOfSpades = new Card(Rank.FOUR, Suit.SPADES)
export const fiveOfSpades = new Card(Rank.FIVE, Suit.SPADES)
export const sixOfSpades = new Card(Rank.SIX, Suit.SPADES)
export const sevenOfSpades = new Card(Rank.SEVEN, Suit.SPADES)
export const eightOfSpades = new Card(Rank.EIGHT, Suit.SPADES)
export const nineOfSpades = new Card(Rank.NINE, Suit.SPADES)
export const tenOfSpades = new Card(Rank.TEN, Suit.SPADES)
export const jackOfSpades = new Card(Rank.JACK, Suit.SPADES)
export const queenOfSpades = new Card(Rank.QUEEN, Suit.SPADES)
export const kingOfSpades = new Card(Rank.KING, Suit.SPADES)
export const aceOfHearts = new Card(Rank.ACE, Suit.HEARTS)
export const twoOfHearts = new Card(Rank.TWO, Suit.HEARTS)
export const threeOfHearts = new Card(Rank.THREE, Suit.HEARTS)
export const fourOfHearts = new Card(Rank.FOUR, Suit.HEARTS)
export const fiveOfHearts = new Card(Rank.FIVE, Suit.HEARTS)
export const sixOfHearts = new Card(Rank.SIX, Suit.HEARTS)
export const sevenOfHearts = new Card(Rank.SEVEN, Suit.HEARTS)
export const eightOfHearts = new Card(Rank.EIGHT, Suit.HEARTS)
export const nineOfHearts = new Card(Rank.NINE, Suit.HEARTS)
export const tenOfHearts = new Card(Rank.TEN, Suit.HEARTS)
export const jackOfHearts = new Card(Rank.JACK, Suit.HEARTS)
export const queenOfHearts = new Card(Rank.QUEEN, Suit.HEARTS)
export const kingOfHearts = new Card(Rank.KING, Suit.HEARTS)
export const aceOfDiamonds = new Card(Rank.ACE, Suit.DIAMONDS)
export const twoOfDiamonds = new Card(Rank.TWO, Suit.DIAMONDS)
export const threeOfDiamonds = new Card(Rank.THREE, Suit.DIAMONDS)
export const fourOfDiamonds = new Card(Rank.FOUR, Suit.DIAMONDS)
export const fiveOfDiamonds = new Card(Rank.FIVE, Suit.DIAMONDS)
export const sixOfDiamonds = new Card(Rank.SIX, Suit.DIAMONDS)
export const sevenOfDiamonds = new Card(Rank.SEVEN, Suit.DIAMONDS)
export const eightOfDiamonds = new Card(Rank.EIGHT, Suit.DIAMONDS)
export const nineOfDiamonds = new Card(Rank.NINE, Suit.DIAMONDS)
export const tenOfDiamonds = new Card(Rank.TEN, Suit.DIAMONDS)
export const jackOfDiamonds = new Card(Rank.JACK, Suit.DIAMONDS)
export const queenOfDiamonds = new Card(Rank.QUEEN, Suit.DIAMONDS)
export const kingOfDiamonds = new Card(Rank.KING, Suit.DIAMONDS)
export const aceOfClubs = new Card(Rank.ACE, Suit.CLUBS)
export const twoOfClubs = new Card(Rank.TWO, Suit.CLUBS)
export const threeOfClubs = new Card(Rank.THREE, Suit.CLUBS)
export const fourOfClubs = new Card(Rank.FOUR, Suit.CLUBS)
export const fiveOfClubs = new Card(Rank.FIVE, Suit.CLUBS)
export const sixOfClubs = new Card(Rank.SIX, Suit.CLUBS)
export const sevenOfClubs = new Card(Rank.SEVEN, Suit.CLUBS)
export const eightOfClubs = new Card(Rank.EIGHT, Suit.CLUBS)
export const nineOfClubs = new Card(Rank.NINE, Suit.CLUBS)
export const tenOfClubs = new Card(Rank.TEN, Suit.CLUBS)
export const jackOfClubs = new Card(Rank.JACK, Suit.CLUBS)
export const queenOfClubs = new Card(Rank.QUEEN, Suit.CLUBS)
export const kingOfClubs = new Card(Rank.KING, Suit.CLUBS)

export function when(description: string, fn: (this: any) => void): void {
  describe(`when ${description}`, fn)
}

export function and(description: string, fn: (this: any) => void): void {
  describe(`and ${description}`, fn)
}

;(global as any).when = when
;(global as any).and = and
;(global as any).aceOfSpades = aceOfSpades
;(global as any).twoOfSpades = twoOfSpades
;(global as any).threeOfSpades = threeOfSpades
;(global as any).fourOfSpades = fourOfSpades
;(global as any).fiveOfSpades = fiveOfSpades
;(global as any).sixOfSpades = sixOfSpades
;(global as any).sevenOfSpades = sevenOfSpades
;(global as any).eightOfSpades = eightOfSpades
;(global as any).nineOfSpades = nineOfSpades
;(global as any).tenOfSpades = tenOfSpades
;(global as any).jackOfSpades = jackOfSpades
;(global as any).queenOfSpades = queenOfSpades
;(global as any).kingOfSpades = kingOfSpades
;(global as any).aceOfHearts = aceOfHearts
;(global as any).twoOfHearts = twoOfHearts
;(global as any).threeOfHearts = threeOfHearts
;(global as any).fourOfHearts = fourOfHearts
;(global as any).fiveOfHearts = fiveOfHearts
;(global as any).sixOfHearts = sixOfHearts
;(global as any).sevenOfHearts = sevenOfHearts
;(global as any).eightOfHearts = eightOfHearts
;(global as any).nineOfHearts = nineOfHearts
;(global as any).tenOfHearts = tenOfHearts
;(global as any).jackOfHearts = jackOfHearts
;(global as any).queenOfHearts = queenOfHearts
;(global as any).kingOfHearts = kingOfHearts
;(global as any).aceOfDiamonds = aceOfDiamonds
;(global as any).twoOfDiamonds = twoOfDiamonds
;(global as any).threeOfDiamonds = threeOfDiamonds
;(global as any).fourOfDiamonds = fourOfDiamonds
;(global as any).fiveOfDiamonds = fiveOfDiamonds
;(global as any).sixOfDiamonds = sixOfDiamonds
;(global as any).sevenOfDiamonds = sevenOfDiamonds
;(global as any).eightOfDiamonds = eightOfDiamonds
;(global as any).nineOfDiamonds = nineOfDiamonds
;(global as any).tenOfDiamonds = tenOfDiamonds
;(global as any).jackOfDiamonds = jackOfDiamonds
;(global as any).queenOfDiamonds = queenOfDiamonds
;(global as any).kingOfDiamonds = kingOfDiamonds
;(global as any).aceOfClubs = aceOfClubs
;(global as any).twoOfClubs = twoOfClubs
;(global as any).threeOfClubs = threeOfClubs
;(global as any).fourOfClubs = fourOfClubs
;(global as any).fiveOfClubs = fiveOfClubs
;(global as any).sixOfClubs = sixOfClubs
;(global as any).sevenOfClubs = sevenOfClubs
;(global as any).eightOfClubs = eightOfClubs
;(global as any).nineOfClubs = nineOfClubs
;(global as any).tenOfClubs = tenOfClubs
;(global as any).jackOfClubs = jackOfClubs
;(global as any).queenOfClubs = queenOfClubs
;(global as any).kingOfClubs = kingOfClubs
